### ISSUE TITLE
Add space between input field and button

### ISSUE THREAD

**Issue by E-fais** [Saadat-B/FSJS-Shopify-Clone#1]
![New Issue · zainalsaleem_portfolio - Google Chrome 21-02-2023 6 46 03 PM](https://user-images.githubusercontent.com/102040088/220393107-1f9a2922-43fe-4d4e-b125-43bf568cc91e.png)

I would like to work on this issue.

**Comment by Saadat-B** [comment]
Thank you for raising the issue 😄
Assigned it to you 👍🏻
